name: pyargos-shred-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - joblib
  - tensorboard
  - pandas
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
      - adelie
      - arviz
      - bambi
      - bayeux-ml
      - flowmc == 0.3.4
      - jax[cuda12]==0.5
      - gurobipy
      - pysindy
      - torchdyn
      - dill
